package za.co.entelect.tools.sample.repository;

import za.co.entelect.tools.sample.model.ppm.DhMddbMv;
import java.lang.Long;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Entelect Tools(Spring JPA Plugin) on Thu Dec 14 14:47:54 CAT 2017
* User ronald22
*/
@Repository
public interface DhMddbMvRepository extends JpaRepository<DhMddbMv, Long> {

}
