package za.co.entelect.tools.sample.service;

import za.co.entelect.tools.sample.model.ppm.DhMddbMv;
import java.lang.Long;
import za.co.entelect.tools.sample.repository.DhMddbMvRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Entelect Tools(Spring JPA Plugin) on Thu Dec 14 14:47:54 CAT 2017
* User ronald22
*/
@Service
@Transactional
public class DhMddbMvService extends AbstractService<DhMddbMv, Long, DhMddbMvRepository> {

    @Autowired
    public DhMddbMvService(DhMddbMvRepository repository) {
        super(repository);
    }
}
