package za.co.entelect.tools.sample.service;

import za.co.entelect.tools.sample.model.Person;
import java.lang.Long;
import za.co.entelect.tools.sample.repository.PersonRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* Generated by Entelect Tools(Spring JPA Plugin) on Thu Dec 14 14:47:54 CAT 2017
* User ronald22
*/
@Service
@Transactional
public class PersonService extends AbstractService<Person, Long, PersonRepository> {

    @Autowired
    public PersonService(PersonRepository repository) {
        super(repository);
    }
}
