package za.co.entelect.tools.sample.model.ppm;
// Generated Sep 18, 2017 12:22:40 PM by Hibernate Tools 5.0.1.Final


import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * DhMddbMv generated by hbm2java
 */
@Entity
@Table(name="DH_MDDB_MV"
    ,schema="PR_CPS"
)
public class DhMddbMv implements java.io.Serializable {


     private long pharmItemId;
     private String extRefCd;
     private String prodName;
     private Date dateTo;
     private String manfCd;
     private Integer manfSeqCd;
     private String manfName;
     private String labellerCode;
     private String catalogueNo;
     private String strength;
     private String strengthUom;
     private String dosageFormId;
     private BigDecimal numberOfUses;
     private BigDecimal packSize;
     private String dispUnitCode;
     private Long dsgUnitOfMeasr;
     private String gpi;
     private String gpiDescription;
     private String systemicId;
     private String rxOtc;
     private String thirdPartyRes;
     private String desi;
     private String multiSrc;
     private String reimbrsmt;
     private String intExt;
     private String snglOrComb;
     private String rtOfAdmin;
     private String deaClass;
     private String teeClass;
     private String mddbDosage;

    public DhMddbMv() {
    }

	
    public DhMddbMv(long pharmItemId, String extRefCd, String prodName, Date dateTo, BigDecimal packSize, String gpi, String gpiDescription) {
        this.pharmItemId = pharmItemId;
        this.extRefCd = extRefCd;
        this.prodName = prodName;
        this.dateTo = dateTo;
        this.packSize = packSize;
        this.gpi = gpi;
        this.gpiDescription = gpiDescription;
    }
    public DhMddbMv(long pharmItemId, String extRefCd, String prodName, Date dateTo, String manfCd, Integer manfSeqCd, String manfName, String labellerCode, String catalogueNo, String strength, String strengthUom, String dosageFormId, BigDecimal numberOfUses, BigDecimal packSize, String dispUnitCode, Long dsgUnitOfMeasr, String gpi, String gpiDescription, String systemicId, String rxOtc, String thirdPartyRes, String desi, String multiSrc, String reimbrsmt, String intExt, String snglOrComb, String rtOfAdmin, String deaClass, String teeClass, String mddbDosage) {
       this.pharmItemId = pharmItemId;
       this.extRefCd = extRefCd;
       this.prodName = prodName;
       this.dateTo = dateTo;
       this.manfCd = manfCd;
       this.manfSeqCd = manfSeqCd;
       this.manfName = manfName;
       this.labellerCode = labellerCode;
       this.catalogueNo = catalogueNo;
       this.strength = strength;
       this.strengthUom = strengthUom;
       this.dosageFormId = dosageFormId;
       this.numberOfUses = numberOfUses;
       this.packSize = packSize;
       this.dispUnitCode = dispUnitCode;
       this.dsgUnitOfMeasr = dsgUnitOfMeasr;
       this.gpi = gpi;
       this.gpiDescription = gpiDescription;
       this.systemicId = systemicId;
       this.rxOtc = rxOtc;
       this.thirdPartyRes = thirdPartyRes;
       this.desi = desi;
       this.multiSrc = multiSrc;
       this.reimbrsmt = reimbrsmt;
       this.intExt = intExt;
       this.snglOrComb = snglOrComb;
       this.rtOfAdmin = rtOfAdmin;
       this.deaClass = deaClass;
       this.teeClass = teeClass;
       this.mddbDosage = mddbDosage;
    }
   
     @Id 

    
    @Column(name="PHARM_ITEM_ID", nullable=false, precision=10, scale=0)
    public long getPharmItemId() {
        return this.pharmItemId;
    }
    
    public void setPharmItemId(long pharmItemId) {
        this.pharmItemId = pharmItemId;
    }

    
    @Column(name="EXT_REF_CD", nullable=false, length=20)
    public String getExtRefCd() {
        return this.extRefCd;
    }
    
    public void setExtRefCd(String extRefCd) {
        this.extRefCd = extRefCd;
    }

    
    @Column(name="PROD_NAME", nullable=false, length=150)
    public String getProdName() {
        return this.prodName;
    }
    
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_TO", nullable=false, length=7)
    public Date getDateTo() {
        return this.dateTo;
    }
    
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    
    @Column(name="MANF_CD", length=10)
    public String getManfCd() {
        return this.manfCd;
    }
    
    public void setManfCd(String manfCd) {
        this.manfCd = manfCd;
    }

    
    @Column(name="MANF_SEQ_CD", precision=5, scale=0)
    public Integer getManfSeqCd() {
        return this.manfSeqCd;
    }
    
    public void setManfSeqCd(Integer manfSeqCd) {
        this.manfSeqCd = manfSeqCd;
    }

    
    @Column(name="MANF_NAME", length=100)
    public String getManfName() {
        return this.manfName;
    }
    
    public void setManfName(String manfName) {
        this.manfName = manfName;
    }

    
    @Column(name="LABELLER_CODE", length=100)
    public String getLabellerCode() {
        return this.labellerCode;
    }
    
    public void setLabellerCode(String labellerCode) {
        this.labellerCode = labellerCode;
    }

    
    @Column(name="CATALOGUE_NO", length=40)
    public String getCatalogueNo() {
        return this.catalogueNo;
    }
    
    public void setCatalogueNo(String catalogueNo) {
        this.catalogueNo = catalogueNo;
    }

    
    @Column(name="STRENGTH", length=50)
    public String getStrength() {
        return this.strength;
    }
    
    public void setStrength(String strength) {
        this.strength = strength;
    }

    
    @Column(name="STRENGTH_UOM", length=25)
    public String getStrengthUom() {
        return this.strengthUom;
    }
    
    public void setStrengthUom(String strengthUom) {
        this.strengthUom = strengthUom;
    }

    
    @Column(name="DOSAGE_FORM_ID", length=3)
    public String getDosageFormId() {
        return this.dosageFormId;
    }
    
    public void setDosageFormId(String dosageFormId) {
        this.dosageFormId = dosageFormId;
    }

    
    @Column(name="NUMBER_OF_USES", precision=10)
    public BigDecimal getNumberOfUses() {
        return this.numberOfUses;
    }
    
    public void setNumberOfUses(BigDecimal numberOfUses) {
        this.numberOfUses = numberOfUses;
    }

    
    @Column(name="PACK_SIZE", nullable=false, precision=12)
    public BigDecimal getPackSize() {
        return this.packSize;
    }
    
    public void setPackSize(BigDecimal packSize) {
        this.packSize = packSize;
    }

    
    @Column(name="DISP_UNIT_CODE", length=20)
    public String getDispUnitCode() {
        return this.dispUnitCode;
    }
    
    public void setDispUnitCode(String dispUnitCode) {
        this.dispUnitCode = dispUnitCode;
    }

    
    @Column(name="DSG_UNIT_OF_MEASR", precision=10, scale=0)
    public Long getDsgUnitOfMeasr() {
        return this.dsgUnitOfMeasr;
    }
    
    public void setDsgUnitOfMeasr(Long dsgUnitOfMeasr) {
        this.dsgUnitOfMeasr = dsgUnitOfMeasr;
    }

    
    @Column(name="GPI", nullable=false, length=100)
    public String getGpi() {
        return this.gpi;
    }
    
    public void setGpi(String gpi) {
        this.gpi = gpi;
    }

    
    @Column(name="GPI_DESCRIPTION", nullable=false, length=300)
    public String getGpiDescription() {
        return this.gpiDescription;
    }
    
    public void setGpiDescription(String gpiDescription) {
        this.gpiDescription = gpiDescription;
    }

    
    @Column(name="SYSTEMIC_ID", length=1)
    public String getSystemicId() {
        return this.systemicId;
    }
    
    public void setSystemicId(String systemicId) {
        this.systemicId = systemicId;
    }

    
    @Column(name="RX_OTC", length=1)
    public String getRxOtc() {
        return this.rxOtc;
    }
    
    public void setRxOtc(String rxOtc) {
        this.rxOtc = rxOtc;
    }

    
    @Column(name="THIRD_PARTY_RES", length=1)
    public String getThirdPartyRes() {
        return this.thirdPartyRes;
    }
    
    public void setThirdPartyRes(String thirdPartyRes) {
        this.thirdPartyRes = thirdPartyRes;
    }

    
    @Column(name="DESI", length=1)
    public String getDesi() {
        return this.desi;
    }
    
    public void setDesi(String desi) {
        this.desi = desi;
    }

    
    @Column(name="MULTI_SRC", length=1)
    public String getMultiSrc() {
        return this.multiSrc;
    }
    
    public void setMultiSrc(String multiSrc) {
        this.multiSrc = multiSrc;
    }

    
    @Column(name="REIMBRSMT", length=1)
    public String getReimbrsmt() {
        return this.reimbrsmt;
    }
    
    public void setReimbrsmt(String reimbrsmt) {
        this.reimbrsmt = reimbrsmt;
    }

    
    @Column(name="INT_EXT", length=1)
    public String getIntExt() {
        return this.intExt;
    }
    
    public void setIntExt(String intExt) {
        this.intExt = intExt;
    }

    
    @Column(name="SNGL_OR_COMB", length=1)
    public String getSnglOrComb() {
        return this.snglOrComb;
    }
    
    public void setSnglOrComb(String snglOrComb) {
        this.snglOrComb = snglOrComb;
    }

    
    @Column(name="RT_OF_ADMIN", length=3)
    public String getRtOfAdmin() {
        return this.rtOfAdmin;
    }
    
    public void setRtOfAdmin(String rtOfAdmin) {
        this.rtOfAdmin = rtOfAdmin;
    }

    
    @Column(name="DEA_CLASS", length=30)
    public String getDeaClass() {
        return this.deaClass;
    }
    
    public void setDeaClass(String deaClass) {
        this.deaClass = deaClass;
    }

    
    @Column(name="TEE_CLASS", length=30)
    public String getTeeClass() {
        return this.teeClass;
    }
    
    public void setTeeClass(String teeClass) {
        this.teeClass = teeClass;
    }

    
    @Column(name="MDDB_DOSAGE", length=30)
    public String getMddbDosage() {
        return this.mddbDosage;
    }
    
    public void setMddbDosage(String mddbDosage) {
        this.mddbDosage = mddbDosage;
    }




}


